### ISSUE TITLE
Flavor identifiers need to match OCCI-OS identifiers

### ISSUE THREAD

**Issue by enolfc** [EGI-FCTF/cloud-bdii-provider#20]
Flavour names use to be something like "m1.tiny", this is not a valid OCCI identifier so OCCI-OS does the following substitutions:
term = term_name.strip().replace(' ', '_').replace('.', '-').lower()

this must be correctly shown in the bdii provider

**Comment by arax** [comment]
Any progress on this?

**Comment by enolfc** [comment]
Fixed in #21
